language: python
sudo: required
services:
  - docker
python:
  - "2.7"
install:
  - sudo apt-get update && sudo apt-get -y install docker-engine
  - pip install -U pip
  - pip install -U tox
script:
  - tox
